swagger: "2.0"
info:
 version: "0.0.1"
 title: "predictioninfo"
 description: "A simple service to get processinfo as an example of using swagger -2.0 specification and codegen"
 termsOfService: "http://swagger.io/terms/"
 contact:
  name: "Cloudmesh Prediction Service"
 license:
  name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh"
schemes:
 - "http"
consumes :
 - "application/json"
produces :
 - "application/json"
paths:
 /prediction:
   get:
    description : "Returns prediction information of the hosting server"
    produces:
     - "application/json"
    responses:
     "200":
       description: "Prediction info"

       schema:
         $ref: "#/definitions/PREDICTION"
definitions:
 PREDICTION:
  type: "object"
  required :
   - "model"
  properties:
   model:
    type: "string"

